
### dev
GET {{url}}/user
Accept: application/json

### save
POST {{url}}/user
Content-Type: application/json

{
  "name": "test1",
  "password": "password1"
}

### login
POST {{url}}/login
Content-Type: application/json

{
  "name": "test1",
  "password": "password1"
}

> {%
  client.global.set("token", response.headers.valuesOf("Set-Cookie")[0])
  %}
